### ISSUE TITLE
hardcode-tray icon

### ISSUE THREAD

**Issue by varlesh** [d-s-x/bomi#8]
Hi! Will bee good if you add another icon name for tray icon use from system icon theme on linux:
`bomi-tray`
If `bomi-tray` available > used from icon theme, if not > used `bomi` from binary.
Thx :)

**Comment by d-s-x** [comment]
@varlesh,

that's a valid suggestion, however I don't have that much spare time to implement it.
Honestly, I don't like this tray function in the first place so I'd rather remove it completely instead (I won't because why bother if it can be disabled? :wink:).

You are welcome to create a pull-request. But please note this repo is not official so probably almost no one will benefit from it.

**Comment by varlesh** [comment]
Автор забросил такой хороший плеер, потому и пишу сюда... здесь хоть, какая-то активность.  Я бы создал PR и поправил сам если бы умел и знал как, не программист к сожалению. Просто люблю когда ДЕ в едином стиле :)
Удалять опцию не вижу смысла, так как она же отключается в настройках

**Comment by d-s-x** [comment]
@varlesh,

> Автор забросил такой хороший плеер

Потому что невозможно поддерживать в одиночку форк mpv: он слишком быстро развивается. Думаю, единственный путь в будущее: удалить все кастомизации и линковаться с системным mpv.

>  Я бы создал PR и поправил сам если бы умел и знал как

если есть свободное время, то можешь погуглить и научиться.

> Просто люблю когда ДЕ в едином стиле

можешь поменять картинку в исходниках и перекомпилировать.

> Удалять опцию не вижу смысла, так как она же отключается в настройках

Я то же самое сказал.
